### PR TITLE
Use local / unqualified name for base-optimizer image

### PR DESCRIPTION
**Pull request by maurolacy**
An attempt at fixing "`base-optimizer` not found" issues.

### CODE REVIEW

**Comment by maurolacy** [comment]
Try `docker image inspect base-optimizer:latest`, and take a look at the "Architecture" field.

I will happily work on this if somebody grants me access to a M1 machine.

**Comment by harryscholes** [comment]
Architecture field says `arm64`. Here's the whole output in case it's useful

```
❯ docker image inspect base-optimizer:latest
[
    {
        "Id": "sha256:6c4b344ce8cf0424f1e73fe9ff6fbe4f17831cbd83c40ba1dec1a79f213f30fc",
        "RepoTags": [
            "base-optimizer:0.11.5",
            "base-optimizer:latest"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-08-11T08:31:47.304098503Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "RUSTUP_HOME=/usr/local/rustup",
                "CARGO_HOME=/usr/local/cargo",
                "RUST_VERSION=1.54.0"
            ],
            "Cmd": [
                "/bin/sh"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux",
        "Size": 983747565,
        "VirtualSize": 983747565,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/tgr2gnoahmosqk11gdeccvi4y/diff:/var/lib/docker/overlay2/nkr74gyb3effnny21ppw4jgn2/diff:/var/lib/docker/overlay2/mev4czw74exyuy39o5c1zaxz0/diff:/var/lib/docker/overlay2/tllwmsri1lixxcmnu7df09ef5/diff:/var/lib/docker/overlay2/znj0xqm1tedn9sop3p9m33pbv/diff:/var/lib/docker/overlay2/aobf1nfuwwsmh4fpo5zbej2rk/diff:/var/lib/docker/overlay2/skevfodsto33cyu0302ito2ui/diff:/var/lib/docker/overlay2/jnms9n8n2akxfgezwjiakyrbg/diff:/var/lib/docker/overlay2/amp05kh6t0bhybqyxe7xdr17h/diff:/var/lib/docker/overlay2/cd02786481ad6bfb21d7bf82c11adec03663c4b614f8398c626a4382a98234aa/diff:/var/lib/docker/overlay2/edd7c652556baa7a7104d8052304a803bcccb04ec86c4c218e44a458e4c96df7/diff:/var/lib/docker/overlay2/4d7decc9c30ffe8df193fed24cd4e6837bb44e1b125619bf63813b86bb8d910f/diff",
                "MergedDir": "/var/lib/docker/overlay2/qhwuu3sgysc1o0unm1ehljpkq/merged",
                "UpperDir": "/var/lib/docker/overlay2/qhwuu3sgysc1o0unm1ehljpkq/diff",
                "WorkDir": "/var/lib/docker/overlay2/qhwuu3sgysc1o0unm1ehljpkq/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:5bfa694cc00ae6e2e670e35d19d7fb0c2ee9b90eb11d684e1b58980995df0528",
                "sha256:8524608d625202f5d64870decadc49c63e162590b94ee35be861d1d518776df0",
                "sha256:195474d0ae61abf9e7079de9546d91732b5c3fa91a4a8002b9617f3cb80e35a4",
                "sha256:4bbe79314d0286cec8ea72fadbb05f15b8419a9c046787f9220796e8e1791476",
                "sha256:c8dca8c29534c071d4150137dcf10956f241fdb97cf47cdfbbf3e8ad11070c79",
                "sha256:19d166223a6f6023ee1bcd1bfe35f2d692afc5d0e30f9403e452f1ac9f4bd70b",
                "sha256:feefc2a5ce41c35dfb2fc379dd2fe70a0c6b7fc343c2488df8a5c5522af103d5",
                "sha256:415583b3bf12df139643c628fffebd058cf7792ec6ee22bda7ff3842485b6997",
                "sha256:0748ded965b81e9bf7f0072dd743deca1e15685bfc3477729f5354306c5e4f8e",
                "sha256:1e6f644202f5a220e0f574c26ac845170ceac89ad4fb102edaa0542d31204c36",
                "sha256:a42e16d4d905109ace356002f7cd16394dc87b7472acaf10b87622c0429a587c",
                "sha256:e90fba7276bcd2d392bcbdb4db97830df01b14fdf28784cb52ff8f31a60109b9",
                "sha256:a9959e25deb629eefbd78ee1a21433d659d986e5cf6fcd4f8ed034cb65333b12"
            ]
        },
        "Metadata": {
            "LastTagTime": "2021-08-11T08:31:57.918838425Z"
        }
    }
]
```

**Comment by maurolacy** [comment]
Makes sense.

I guess a relatively simple way around this would be to use `docker buildx` and specify the platform / arch as `amd64`.

**Comment by webmaster128** [comment]
Strange that docker build tries to fetch meta information about the local image.

Could you try if this has something to do with the introduction of buildkit? See

- https://docs.docker.com/develop/develop-images/build_enhancements/
- https://stackoverflow.com/a/64466563/2013738

**Comment by webmaster128** [comment]
According to https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage we can write all 3 stages in a single dockerfile. Then use this example use case to differentiate between the two outputs

> Using a debug stage with all debugging symbols or tools enabled, and a lean production stage

**Comment by maurolacy** [comment]
> Strange that docker build tries to fetch meta information about the local image.
> 
> Could you try if this has something to do with the introduction of buildkit? See
> 
> * https://docs.docker.com/develop/develop-images/build_enhancements/
> * https://stackoverflow.com/a/64466563/2013738

May be. This certainly looks like a docker bug.

**Comment by maurolacy** [comment]
> According to https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage we can write all 3 stages in a single dockerfile. Then use this example use case to differentiate between the two outputs
> 
> > Using a debug stage with all debugging symbols or tools enabled, and a lean production stage

There's a not so old version / tag of rust-optimizer that doesn't have a `base-optimizer`. That could be another way to try confirm / work around this.

**Comment by webmaster128** [comment]
I'm getting the impression this is not a docker bug but we use docker in an unintended way with this unpublished intermediate image. This was no problem before, but now docker build is searching for `base-optimizer` metadata on dockerhub that is simply not there. https://docs.docker.com/develop/develop-images/multistage-build seems to be what we want to do instead.

**Comment by maurolacy** [comment]
> I'm getting the impression this is not a docker bug but we use docker in an unintended way with this unpublished intermediate image. This was no problem before, but now docker build is searching for `base-optimizer` metadata on dockerhub that is simply not there. https://docs.docker.com/develop/develop-images/multistage-build seems to be what we want to do instead.

https://stackoverflow.com/questions/20481225/how-can-i-use-a-local-image-as-the-base-image-with-a-dockerfile

Check the  second answer: Don't specify `--pull=true` when running the `docker build` command.

**Comment by harryscholes** [comment]
I've used multistage Docker builds in another project. It works very well and seems well suited to our use case

**Pull request closed without merging**
